- name: Get Yugabyte Package
  unarchive:
    src: "https://downloads.yugabyte.com/{{ TAR_FILE }}"
    dest: "{{ software_dir }}"
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: yes

- name: Setting installation dir variables
  set_fact:
    install_dir: "{{ software_dir }}/yugabyte-{{ YB_VERSION }}"
    config_dir: "{{ conf_dir }}"
    
- name: Execute Yugabyte installation
  shell: "cd {{ install_dir }}; nohup ./bin/post_install.sh > {{ install_dir }}/install.log 2>&1 & sleep 1"

- name: Wait until installation completed file is there
  wait_for:
    path: "{{ install_dir }}/.post_install.sh.completed"
    state: present
    timeout: 300

- name: Create symbolic link for installation
  file:
    src: "{{ install_dir }}"
    dest: "{{ item }}"
    state: link
  with_items:
    - "{{ link_destinations }}"

